### ISSUE TITLE
SMARTS parsing bug

### ISSUE THREAD

**Issue by OliverBScott** [Actelion/openchemlib#102]
Hi there! I have noticed a bug when parsing atoms with a specified number of Hydrogens, without a logical operator (`&`, `;`) i.e. `[CH2]`. It seems that openchemlib does not respect this format with the parsed query allowing any number of hydrogens. The Daylight manual refers to this format in a couple of places:

> Note that atomic primitive H can have two meanings, implying a property or the element itself. [H] means hydrogen atom. [*H2] means any atom with exactly two hydrogens attached

And in the Examples:

| [n;H1]  | H-pyrrole nitrogen  |
|--------|--------------------|
| [n&H1] | same as above       | 
| [nH1]   | same as above        | 

It would be great if this format could be accepted, given that tools such as Marvin-JS write SMARTS in this format.

Thanks

**Comment by thsa** [comment]
there were some SMARTS improvement recently. Among other, also these issues seem to be covered. However, in OpenChemLib SMARTS parsing will always be an approximation, because OpenChemLib and SMARTS concepts do largely overlap, but not every SMARTS feature can exactly be represented in OpenChemLib and vice versa. For instance, the ',' allows to logically OR multiple different atoms, i.e. atomic numbers, which is translated into an atom list with multiple entries. If, if these each of these atoms carry different query features, this cannot be represented in OpenChemLib. Negative recursive SMARTS are translated into exclude groups, which even works with multiple ones. However, recursive SMARTS that contain recursive SMARTS themselves, cannot be translated. Single positive recursive SMARTS are tricky, multiple ones cannot be translated.
