### ISSUE TITLE
Packaging problems

### ISSUE THREAD

**Issue by andcastillo** [Actelion/openchemlib#2]
There is many misplaced classes in the project. i.e: openchemlib/src/com/actelion/research/chem/AbstractDescriptorHandlerFP.java
which package declaration is: package com.actelion.research.chem.descriptor

**Comment by thsa** [comment]
Dear Andres,

I confirmed the problem and appologize for it. At Actelion we moved our
internal version control system
from Perfoce to Git and maybe the problems are connected to this. Of course
this should never happen and
I will personally make sure that this is fixed as quicly as possible.

Thank you for commenting and kind regards,

Thomas Sander

On Sun, Nov 8, 2015 at 3:53 PM, andres castillo <notifications@github.com>
wrote:

> There is many misplaced classes in the project. i.e:
> openchemlib/src/com/actelion/research/chem/AbstractDescriptorHandlerFP.java
> which package declaration is: package com.actelion.research.chem.descriptor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Actelion/openchemlib/issues/2>.
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.
