### ISSUE TITLE
Molecule: setFragment is not invertible

### ISSUE THREAD

**Issue by targos** [Actelion/openchemlib#4]
I have the following IDCode: `gOp@DjWkB@@LYdxA@` which represents the fragment
![image](https://cloud.githubusercontent.com/assets/2352663/11300156/0d4c8e8c-8f8d-11e5-975b-5ac928fdc5f2.png)

If I load this IDCode in variable `m` and call successively `m.setFragment()`, here is what I get:
```
m.getIDCode() // gOp@DjWkB@@LYdxA@
m.setFragment(false)
m.getIDCode() // gOp@DjWkB@@@
m.setFragment(true)
m.getIDCode() // gOp@DjWkB@@H
```

By doing this, I lose the query features of the original fragment. Is that expected ?

**Comment by rufenerc** [comment]
Hello Michael

This is by design: The molecule removes the query features when changed by
setFragment(false). If you need to keep the features, there's only the way
to keep a copy of the original.

Sorry.

Christian


On Fri, Nov 20, 2015 at 1:50 PM, Michaël Zasso <notifications@github.com>
wrote:

> I have the following IDCode: gOp@DjWkB@@LYdxA@ which represents the
> fragment
> [image: image]
> <https://cloud.githubusercontent.com/assets/2352663/11300156/0d4c8e8c-8f8d-11e5-975b-5ac928fdc5f2.png>
>
> If I load this IDCode in variable m and call successively m.setFragment(),
> here is what I get:
>
> m.getIDCode() // gOp@DjWkB@@LYdxA@
> m.setFragment(false)
> m.getIDCode() // gOp@DjWkB@@@
> m.setFragment(true)
> m.getIDCode() // gOp@DjWkB@@H
>
> By doing this, I lose the query features of the original fragment. Is that
> expected ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Actelion/openchemlib/issues/4>.
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.

**Comment by targos** [comment]
OK, no problem. I just wanted to make sure I didn't miss something.
Thanks.
