### ISSUE TITLE
Maven repo

### ISSUE THREAD

**Issue by tdudgeon** [Actelion/openchemlib#5]
Are there any plan to push the built jar file to Maven repositories like Maven Central and JCenter?
Thanks
Tiim

**Comment by thsa** [comment]
Dear Tim,

we have discussed that internally and will most likely push snapshots
whenever the GitHub source repository changes.
In addition to that we will also create and push defined versions in
regular intervals.

We will have a final discussion next week, when one of our experts is back
from vacation and we will set it up then very soon.

Did you look into the code and will/can you use it for something?

Best wishes,

Thomas


On Tue, Apr 5, 2016 at 3:07 PM, Tim Dudgeon <notifications@github.com>
wrote:

> Are there any plan to push the built jar file to Maven repositories like
> Maven Central and JCenter?
> Thanks
> Tiim
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Actelion/openchemlib/issues/5>
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.

**Comment by tdudgeon** [comment]
Hi Thomas,

Thanks. Having this in a Maven repo would certainly be handy.

Yes, I have started to make use of it. initially just for molecular 
property predictions.
Actually, I'm likely to be in Basel again the week commencing May 9, and 
would like to try to meet up with you again to discuss how I can make 
further use of it if that was possible.

Tim

**Comment by thsa** [comment]
Dear Tim,

in May I should be available. Please let me know, when you are in the
vicinity. Then I would be glad to meet you...

Best wishes,

Thomas

On Thu, Apr 7, 2016 at 5:02 PM, Tim Dudgeon <notifications@github.com>
wrote:

> Hi Thomas,
>
> Thanks. Having this in a Maven repo would certainly be handy.
>
> Yes, I have started to make use of it. initially just for molecular
> property predictions.
> Actually, I'm likely to be in Basel again the week commencing May 9, and
> would like to try to meet up with you again to discuss how I can make
> further use of it if that was possible.
>
> Tim
>
>
>
> On 07/04/2016 15:31, thsa wrote:
> > Dear Tim,
> >
> > we have discussed that internally and will most likely push snapshots
> > whenever the GitHub source repository changes.
> > In addition to that we will also create and push defined versions in
> > regular intervals.
> >
> > We will have a final discussion next week, when one of our experts is
> back
> > from vacation and we will set it up then very soon.
> >
> > Did you look into the code and will/can you use it for something?
> >
> > Best wishes,
> >
> > Thomas
> >
> >
> > On Tue, Apr 5, 2016 at 3:07 PM, Tim Dudgeon <notifications@github.com>
> > wrote:
> >
> > > Are there any plan to push the built jar file to Maven repositories
> like
> > > Maven Central and JCenter?
> > > Thanks
> > > Tiim
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Actelion/openchemlib/issues/5>
> > >
> >
> > --
> >
> > The information of this email and in any file transmitted with it is
> > strictly confidential and may be legally privileged.
> > It is intended solely for the addressee. If you are not the intended
> > recipient, any copying, distribution or any other use of this email is
> > prohibited and may be unlawful. In such case, you should please notify
> > the
> > sender immediately and destroy this email.
> > The content of this email is not legally binding unless confirmed by
> > letter.
> > Any views expressed in this message are those of the individual sender,
> > except where the message states otherwise and the sender is authorized to
> > state them to be the views of the sender's company.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Actelion/openchemlib/issues/5#issuecomment-206932680
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Actelion/openchemlib/issues/5#issuecomment-206943228>
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.

**Comment by artaius** [comment]
Dear all,

As discussed the openchemlib is now available through Maven Central:
http://search.maven.org/#search|ga|1|openchemlib

Releases are triggered on the 1st of every month or upon request. Snapshots
are created every Monday morning.

The naming scheme is as follows:
YEAR.MONTH.RELEASE_WITHIN_MONTH

Do not hesitate to contact me if you should have any questions.

Best regards,
Roman


Roman Bär

Drug Discovery Information Management
Actelion Pharmaceuticals Ltd. • Gewerbestrasse 16 • CH-4123 Allschwil •
Switzerland
VOIP  92 85 51 • phone +41 61 565 85 51
roman.baer@actelion.com • www.actelion.com
Address for visitors: Hegenheimermattweg 91

On Thu, Apr 7, 2016 at 8:50 PM, thsa <notifications@github.com> wrote:

> Dear Tim,
>
> in May I should be available. Please let me know, when you are in the
> vicinity. Then I would be glad to meet you...
>
> Best wishes,
>
> Thomas
>
> On Thu, Apr 7, 2016 at 5:02 PM, Tim Dudgeon <notifications@github.com>
> wrote:
>
> > Hi Thomas,
> >
> > Thanks. Having this in a Maven repo would certainly be handy.
> >
> > Yes, I have started to make use of it. initially just for molecular
> > property predictions.
> > Actually, I'm likely to be in Basel again the week commencing May 9, and
> > would like to try to meet up with you again to discuss how I can make
> > further use of it if that was possible.
> >
> > Tim
> >
> >
> >
> > On 07/04/2016 15:31, thsa wrote:
> > > Dear Tim,
> > >
> > > we have discussed that internally and will most likely push snapshots
> > > whenever the GitHub source repository changes.
> > > In addition to that we will also create and push defined versions in
> > > regular intervals.
> > >
> > > We will have a final discussion next week, when one of our experts is
> > back
> > > from vacation and we will set it up then very soon.
> > >
> > > Did you look into the code and will/can you use it for something?
> > >
> > > Best wishes,
> > >
> > > Thomas
> > >
> > >
> > > On Tue, Apr 5, 2016 at 3:07 PM, Tim Dudgeon <notifications@github.com>
> > > wrote:
> > >
> > > > Are there any plan to push the built jar file to Maven repositories
> > like
> > > > Maven Central and JCenter?
> > > > Thanks
> > > > Tiim
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/Actelion/openchemlib/issues/5>
> > > >
> > >
> > > --
> > >
> > > The information of this email and in any file transmitted with it is
> > > strictly confidential and may be legally privileged.
> > > It is intended solely for the addressee. If you are not the intended
> > > recipient, any copying, distribution or any other use of this email is
> > > prohibited and may be unlawful. In such case, you should please notify
> > > the
> > > sender immediately and destroy this email.
> > > The content of this email is not legally binding unless confirmed by
> > > letter.
> > > Any views expressed in this message are those of the individual sender,
> > > except where the message states otherwise and the sender is authorized
> to
> > > state them to be the views of the sender's company.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/Actelion/openchemlib/issues/5#issuecomment-206932680
> > >
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Actelion/openchemlib/issues/5#issuecomment-206943228
> >
> >
>
> --
>
> The information of this email and in any file transmitted with it is
> strictly confidential and may be legally privileged.
> It is intended solely for the addressee. If you are not the intended
> recipient, any copying, distribution or any other use of this email is
> prohibited and may be unlawful. In such case, you should please notify the
> sender immediately and destroy this email.
> The content of this email is not legally binding unless confirmed by
> letter.
> Any views expressed in this message are those of the individual sender,
> except where the message states otherwise and the sender is authorized to
> state them to be the views of the sender's company.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Actelion/openchemlib/issues/5#issuecomment-207047637>
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.
