### ISSUE TITLE
getPath reorder the atoms !

### ISSUE THREAD

**Issue by lpatiny** [Actelion/openchemlib#56]
@thsa I found an annoying problem in which some atoms in molecule may be reordered calling `getPath``
If I create methane and tag the second atom by changing the atomicNo and adding a custom label, getPath will reorder atoms. This is not the case if we don't create a custom label.
```
 let molecule = OCL.Molecule.fromSmiles('C');
    molecule.addImplicitHydrogens();

    molecule.setAtomicNo(2, 153);
    molecule.setAtomCustomLabel(2, 'H*');
    for (let i = 0; i < molecule.getAllAtoms(); i++) {
      console.log(molecule.getAtomicNo(i)); // 153 is at third position
    }
    molecule.getPath(0, 1, 2);
    console.log('-----');
    for (let i = 0; i < molecule.getAllAtoms(); i++) {
      console.log(molecule.getAtomicNo(i)); // 153 is in second position
    }
```

**Comment by thsa** [comment]
this is the intended behaviour: OpenChemLib always keeps simple hydrogen atoms at the end of the list, because for most methods they are invisible and implicit. If you convert a simple hydrogen to another atom or add a custom label to make it an important hydrogen, then it needs to move to a lower position in the atom list such that all simple hydrogens have higher indexes. At the same time getAtoms() will report an incremented value.
