### ISSUE TITLE
SSSearch Usage

### ISSUE THREAD

**Issue by johnmay** [Actelion/openchemlib#6]
I'm trying to match molecules with the SSSearcher but seem to be missing some setup. Have tried also with IDCodes and varied the SSSearcher match mode. What's missing from this minimal example:

```java
final SmilesParser smipar = new SmilesParser();

final StereoMolecule qry = new StereoMolecule();
final StereoMolecule mol = new StereoMolecule();
        
smipar.parse(qry, "c1ccccc1");
smipar.parse(mol, "c1ccccc1");

final SSSearcher subsearch = new SSSearcher(SSSearcher.cMatchAromDBondToDelocalized);
subsearch.setMol(qry, mol);
System.err.println(subsearch.isFragmentInMolecule()); // false?
````

Thanks,
J

**Comment by thsa** [comment]
Molecule instances can either represent molecules or fragments, which have
different behaviour.
For instance, undefined valences in molecules are considered to be filled
with implicit hydrogens,
while in fragments they are open. When a molecule/fragment is depicted,
this is reflected in the drawing.
Molecules cannot have query features.

The SmilesParser constructs a molecule and not a fragment, while the SSSearcher
expects a fragment
in setMol(qry, mol) as first argument. Incidentally, the second argument
may also be a fragment.
Fragment in fragment search is possible, while molecule in molecule search
is not.

You need to define the query object to be a fragment with
qry.setFragment(true) as below:

final SmilesParser smipar = new SmilesParser();
final StereoMolecule qry = new StereoMolecule();
final StereoMolecule mol = new StereoMolecule();

smipar.parse(qry, "c1ccccc1");
smipar.parse(mol, "c1ccccc1");
qry.setFragment(true);

final SSSearcher subsearch = new SSSearcher();
subsearch.setMol(qry, mol);
System.err.println(subsearch.isFragmentInMolecule()); // false?
}

Hope, this explains it.

Thomas

On Sun, Apr 24, 2016 at 12:17 PM, John May <notifications@github.com> wrote:

> I'm trying to match molecules with the SSSearcher seem to be missing some
> setup. Have tried also with IDCodes and varied the SSSearcher match mode.
> What's missing from this minimal example:
>
> final SmilesParser smipar = new SmilesParser();
> final StereoMolecule qry = new StereoMolecule();final StereoMolecule mol = new StereoMolecule();
>
> smipar.parse(qry, "c1ccccc1");
> smipar.parse(mol, "c1ccccc1");
> final SSSearcher subsearch = new SSSearcher(SSSearcher.cMatchAromDBondToDelocalized);
> subsearch.setMol(qry, mol);System.err.println(subsearch.isFragmentInMolecule()); // false?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Actelion/openchemlib/issues/6>
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.

**Comment by johnmay** [comment]
Thanks Thomas that does explain it, tried and worked as expected. Wondering though why this case still failed? Even with valences, benzene should match benzene as a subgraph isomorphism.

**Comment by thsa** [comment]
it failed, because the SSSearcher immediately returns false if fragment is
not a fragment.

Thomas

On Mon, Apr 25, 2016 at 11:17 AM, John May <notifications@github.com> wrote:

> Thanks Thomas that does explain it, tried and worked as expected.
> Wondering though why this case still failed? Even with valences, benzene
> should match benzene as a subgraph isomorphism.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Actelion/openchemlib/issues/6#issuecomment-214223371>
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.
