### ISSUE TITLE
Discrepancies in logS prediction

### ISSUE THREAD

**Issue by c-ruttkies** [Actelion/openchemlib#60]
Hi,

I investigated a problem in the PropertyCalculator:

```
public static void main(String[] args) throws Exception {
		String smiles = "O1O[Mg]1"; // [Hydrogen peroxido(2-)-κ2O,O']magnesium
		StereoMolecule molecule = new StereoMolecule();
		SmilesParser sp = new SmilesParser();
		sp.parse(molecule, smiles);

		PropertyCalculator pc = new PropertyCalculator(molecule);
		System.out.println(pc.getLogS());	
		System.out.println(pc.getLogP());
		System.out.println(pc.getLogS());	
}
```
The output is
`
-0.5299999713897705
-0.7239999771118164
-0.49799999594688416
`
I get different values for logS calculated before and after the logP prediction. It seems to only occur for specific molecules (here: O1O[Mg]1). Also found discrepancies for "O[Mg]O".

Best regards,
Christoph

**Comment by thsa** [comment]
I have fixed the issue. While the cLogP-predictor normalized covalent metal bonds to polar ones, the cLogS-predictor didn't, which caused the identification of different atom types before and after normalization (done by cLogP).

A general remark: Both predictors were trained on organic molecules and don't know about minerals and pure salts. Predicted values for anything else than organic molecules are meaningless.

Thomas
________________________________
Von: c-ruttkies <notifications@github.com>
Gesendet: Mittwoch, 19. August 2020 12:13
An: Actelion/openchemlib <openchemlib@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Actelion/openchemlib] Discrepancies in logS prediction (#60)


Hi,

I investigated a problem in the PropertyCalculator:

public static void main(String[] args) throws Exception {

                String smiles = "O1O[Mg]1"; // [Hydrogen peroxido(2-)-κ2O,O']magnesium

                StereoMolecule molecule = new StereoMolecule();

                SmilesParser sp = new SmilesParser();

                sp.parse(molecule, smiles);



                PropertyCalculator pc = new PropertyCalculator(molecule);

                System.out.println(pc.getLogS());

                System.out.println(pc.getLogP());

                System.out.println(pc.getLogS());

}



The output is
-0.5299999713897705 -0.7239999771118164 -0.49799999594688416
I get different values for logS calculated before and after the logP prediction. It seems to only occur for specific molecules (here: O1O[Mg]1). Also found discrepancies for "O[Mg]O".

Best regards,
Christoph

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FActelion%2Fopenchemlib%2Fissues%2F60&data=02%7C01%7Cthomas.sander%40idorsia.com%7Ca286c4fe5863494b13ae08d8442880a7%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637334288028949265&sdata=vB8vDlQP3WSsAompOiPiCTsjDscyPcRidM4YQD6UGic%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBQK6YEPZWW4KJQEOBDSBOQT7ANCNFSM4QEYUAXA&data=02%7C01%7Cthomas.sander%40idorsia.com%7Ca286c4fe5863494b13ae08d8442880a7%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637334288028949265&sdata=D8QJ27MZSH1B5l3o63sGdSH8h6m%2FfVmJuJDC2e61078%3D&reserved=0>.

The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by c-ruttkies** [comment]
Thanks for the quick fix and also for the clarification. 

Best regards,
Christoph

**Comment by c-ruttkies** [comment]
Hi Thomas,

I don't know if this is related but I also found a similar issue with the drug-likeness prediction:
```
public static void main(String[] args) throws Exception {
                String smiles = "O1O[Mg]1"; // [Hydrogen peroxido(2-)-κ2O,O']magnesium
		StereoMolecule molecule = new StereoMolecule();
		SmilesParser sp = new SmilesParser();
		sp.parse(molecule, smiles);
		
		System.out.println(new DruglikenessPredictor().assessDruglikeness(molecule, null));
		
		PropertyCalculator pc = new PropertyCalculator(molecule);
		
		System.out.println(new DruglikenessPredictor().assessDruglikeness(molecule, null));
}
```

This gives me 

`
-10.427499999999998
-1.0
`

Best regards,
Christoph

**Comment by thsa** [comment]
Some of the predictors do a minimal structure normalization before starting the prediction based on structure patterns. Others don't. Thus, if you start from a non-normalized structure and run predictions in various orders, you may end up with inconsistent results. Before predicting anything from chemical structures you should make sure that your structure is standardized, e.g. using the MoleculeStandardizer. Molecules obtained by parsing idcodes should be standardized per-se, because any software creating idcodes is supposed to standardize a molecule before creating an idcode, but if the source is SMILES from an unknown source, your structure may be pretty non-standard...
