### ISSUE TITLE
Different IDCodes for SMILES and MDL MOL

### ISSUE THREAD

**Issue by c-ruttkies** [Actelion/openchemlib#61]
Hi,

I have two StereoMolecule objects of the same molecule created from SMILES and MDL MOL, respectively. The SMILES was generated by openbabel using the MDL MOL file as input, so they should encode exactly the same molecule. Here is my test code:

```java
public class MolStereoTest {

	private String mol1 = "\n" + 
		"  MJ191900                      \n" + 
		"\n" + 
		"  6  5  0  0  0  0  0  0  0  0999 V2000\n" + 
		"   -0.0649    0.4929    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" + 
		"    0.3475    1.2074    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" + 
		"   -0.0649    1.9219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" + 
		"    1.1725    1.2074    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n" + 
		"    0.3475   -0.2214    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n" + 
		"   -0.8899    0.4929    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n" + 
		"  1  2  1  0  0  0  0\n" + 
		"  2  3  1  0  0  0  0\n" + 
		"  2  4  1  6  0  0  0\n" + 
		"  1  5  1  0  0  0  0\n" + 
		"  1  6  2  0  0  0  0\n" + 
		"M  END\n" + 
		"";
	
	private String smiles = "C[C@H](O)C(O)=O";
	
	@Test
	public void test() throws Exception {

		StereoMolecule smimol1 = new StereoMolecule();
		SmilesParser sp = new SmilesParser();
		sp.parse(smimol1, this.smiles);
		
		MolfileParser mp = new MolfileParser();
		
		StereoMolecule mol1 = new StereoMolecule();
		
		mp.parse(mol1, this.mol1);

		assertThat(mol1.getIDCode(), is(smimol1.getIDCode()));
			
	}
	
}
```

I get the assertion error that the resulting IDCodes are different:

> java.lang.AssertionError: 
> Expected: is "gGQ\`@bdwMUM@@"
>     got: "gGQ\`@bdwMULP@"

I would have expected the same IDCodes for both molecules independent of the source format used to generate them. Am I doing sth. wrong here?

Thanks in advance.

Best regards,
Christoph

**Comment by thsa** [comment]
Hi Christoph,

the Molecule encoded in the two idcodes is the same except that in one case it is racemic and in the other a pure enantiomer. The problem is that different chemistry frameworks sometimes need to make assumptions when parsing molecules from smiles or molfiles and these are not necessarily the same. In your case the molfile has not set the 'chiral' flag, which means that the molecule is a racemate. OpenChemLib uses this strictly. Thus, the resulting idcode says it is a racemate.

Evidently OpenBabel sees a stereo bonds and assumes that despite the chiral flag being 0 that the user might have meant the enatiomerically pure compound and creates a SMILES with stereo assignment. Smiles themselves have no way to define whether they are racemic or pure. If there is only one stereo center, it is easy. Typically then the SMILES is the defined enantiomer. If there are more stereo centers, it is completely unclear, whether we have a racemate with relative configurations or just one diastereomer.

In molfiles (version 2) the problem starts with 3 stereo centers, because the chiral flag refers to the molecule and not to individual stereo features. The only way around that is using 'enhanced stereo representation' which was introduced by MDL with the molfile V3 (or V3000). OpenChemLib is consistently using this concept in display, editor, subtructure search, idcodes, etc.

Hope that explains it. I consider that a serious issue with SMILES and molfiles V2, but many information systems still use them and therefore have substantial problems in handling stereo chemistry.

Best wishes,

Thomas
________________________________
Von: c-ruttkies <notifications@github.com>
Gesendet: Donnerstag, 1. Oktober 2020 11:01
An: Actelion/openchemlib <openchemlib@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Actelion/openchemlib] Different IDCodes for SMILES and MDL MOL (#61)


Hi,

I have two StereoMolecule objects of the same molecule created from SMILES and MDL MOL, respectively. The SMILES was generated by openbabel using the MDL MOL file as input, so they should encode exactly the same molecule. Here is my test code:

public class MolStereoTest {

        private String mol1 = "\n" +
                "  MJ191900                      \n" +
                "\n" +
                "  6  5  0  0  0  0  0  0  0  0999 V2000\n" +
                "   -0.0649    0.4929    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
                "    0.3475    1.2074    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
                "   -0.0649    1.9219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
                "    1.1725    1.2074    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n" +
                "    0.3475   -0.2214    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n" +
                "   -0.8899    0.4929    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n" +
                "  1  2  1  0  0  0  0\n" +
                "  2  3  1  0  0  0  0\n" +
                "  2  4  1  6  0  0  0\n" +
                "  1  5  1  0  0  0  0\n" +
                "  1  6  2  0  0  0  0\n" +
                "M  END\n" +
                "";

        private String smiles = "C[C@H](O)C(O)=O";

        @Test
        public void test() throws Exception {

                StereoMolecule smimol1 = new StereoMolecule();
                SmilesParser sp = new SmilesParser();
                sp.parse(smimol1, this.smiles);

                MolfileParser mp = new MolfileParser();

                StereoMolecule mol1 = new StereoMolecule();

                mp.parse(mol1, this.mol1);

                assertThat(mol1.getIDCode(), is(smimol1.getIDCode()));

        }

}

I get the assertion error that the resulting IDCodes are different:

java.lang.AssertionError:
Expected: is "gGQ`@bdwMUM@@"
got: "gGQ`@bdwMULP@"

I would have expected the same IDCodes for both molecules independent of the source format used to generate them. Am I doing sth. wrong here?

Thanks in advance.

Best regards,
Christoph

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FActelion%2Fopenchemlib%2Fissues%2F61&data=02%7C01%7Cthomas.sander%40idorsia.com%7Cf3b9303321c84c08740408d865e89bfa%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637371397007587021&sdata=XSpJzwbrhiqcq%2BrbM%2BNANvehESr14la9b6kbwD0Oss0%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBRYO5QOEGURJGHSJD3SIRAPFANCNFSM4SAERZ4A&data=02%7C01%7Cthomas.sander%40idorsia.com%7Cf3b9303321c84c08740408d865e89bfa%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637371397007587021&sdata=CJHEJBLDAt4SS7qpJqLAPTGNRJis6Sp%2FJdmp5kdpsGo%3D&reserved=0>.

The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by c-ruttkies** [comment]
Hi Thomas,

thanks for the comprehensive response and the clarification. I got your point that the mol file needs the chiral flag in this case. I will prepare a workaround until we switch completely to V3000 and/or IdCodes :) 

Best regards,
Christoph
