### ISSUE TITLE
Support for doublet radicals in molfile parser

### ISSUE THREAD

**Issue by lpatiny** [Actelion/openchemlib#82]
Would it be possible to deal with the doublet radical that is define at the level of the atom line as defined in the specifications ?

![image](https://user-images.githubusercontent.com/1484241/210999818-7edc3f49-91a2-4a29-bcb3-8f3b22bc941c.png)

```
        int chargeDif = parseIntOrSpaces(line.substring(36, 39).trim());
        if (chargeDif != 0) {
          if (chargeDif == 4) {
            mMol.setAtomRadical(atom, Molecule.cAtomRadicalStateD);
          } else {
            mMol.setAtomCharge(atom, 4 - chargeDif);
          }
        }
```

**Comment by thsa** [comment]
is done
________________________________
Von: Luc Patiny ***@***.***>
Gesendet: Freitag, 6. Januar 2023 12:03
An: Actelion/openchemlib ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Actelion/openchemlib] Support for doublet radicals in molfile parser (Issue #82)


Would it be possible to deal with the doublet radical that is define at the level of the atom line as defined in the specifications ?

[image]<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1484241%2F210999818-7edc3f49-91a2-4a29-bcb3-8f3b22bc941c.png&data=05%7C01%7Cthomas.sander%40idorsia.com%7C28af559d856149c60f0d08daefd5b3d8%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C638085998363065533%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ptofil0AVd9rVRnWFtXKuXkZ8uXOq3t1ytHrID%2Fkk7Y%3D&reserved=0>

        int chargeDif = parseIntOrSpaces(line.substring(36, 39).trim());
        if (chargeDif != 0) {
          if (chargeDif == 4) {
            mMol.setAtomRadical(atom, Molecule.cAtomRadicalStateD);
          } else {
            mMol.setAtomCharge(atom, 4 - chargeDif);
          }
        }


—
Reply to this email directly, view it on GitHub<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FActelion%2Fopenchemlib%2Fissues%2F82&data=05%7C01%7Cthomas.sander%40idorsia.com%7C28af559d856149c60f0d08daefd5b3d8%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C638085998363221743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XuVEx9vCL15S6ehqRYECUX5BIno%2Bq4erbtqCu%2BiU5TE%3D&reserved=0>, or unsubscribe<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBUULMH33V63MMXSK5TWQ73ZTANCNFSM6AAAAAATS6ZHEI&data=05%7C01%7Cthomas.sander%40idorsia.com%7C28af559d856149c60f0d08daefd5b3d8%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C638085998363221743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WDgQ%2FOVvDrGJXWAN3dcBAcjYFMti64QSuhWVq%2Fewo6Q%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.
